#!/bin/sh
#
# PROVIDE: mtdaapd mt-daapd
# REQUIRE: DAEMON
# KEYWORD: shutdown
#
# mt-daapd daemon.
#
# Created by Patrick Lemmens for NetBSD and FreeBSD.

. /etc/rc.subr

name="mtdaapd"
realname="mt-daapd"
rcvar=$name
command="/home/defjovi/projects/RT-N56U/source/user/mt-daapd-svn-1696/source/../install/bin/${realname}"
pidfile="/var/run/${realname}.pid"
sig_stop="SIGINT"
 
load_rc_config $name
run_rc_command "$1"